### PR TITLE
Fixed deleting income such that the program does not crash

### LINKED ISSUE #65: Fix deleting income
When delete income is called such that it results in a negative balance due to expenses, the program will crash.

### PR DESCRIPTION
**Pull request by teokj**
Fixes #65 
Removed the error that throws a new BudgetTrackerException and instead just print the error message

### CODE REVIEW

File: src/main/java/commands/DeleteIncomeCommand.java [hunk 1]
```diff
@@ -103,9 +103,9 @@ public void incomeExecute(IncomeManager incomeManager, Ui ui) throws BudgetTrack
             summary.removeIncome(amountToRemove);
             ui.showMessage("Deleted income entry at index " + index);
             System.out.println("Successfully deleted income at index " + index); // logging message
```
Comment (Yshinprograms) [inline src/main/java/commands/DeleteIncomeCommand.java:105]: As per Prof's comments, can just remove these end-of-line comments

**Review by Yshinprograms — APPROVED** [review]
